# Generated by Django 2.2.4 on 2019-08-29 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('blog', '0008_bloglistingcategorypage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogListingCategoryPage',
        ),
    ]
