# Generated by Django 2.2.4 on 2019-08-29 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_delete_bloglistingcategorypage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogdetailpage',
            old_name='blog_image',
            new_name='banner_image',
        ),
    ]
