# Generated by Django 2.2.4 on 2019-08-28 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediasettings',
            name='footer',
            field=models.TextField(blank=True, help_text='text to display under social media icons', null=True),
        ),
    ]
